### ISSUE TITLE
node import/require error

### ISSUE THREAD

**Issue by tosscaster** [linagora/jmap-client#33]
after npm install jmap-client

import jmap from 'jmap-client';
or
var jmap = require('jmap-client');

--------------------------- error
module.js:341
    throw err;
    ^

Error: Cannot find module 'jmap-client'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (E:\Temp\jmap-client\samples\cli\jmap-client-pass-cli.js:11:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by thomas-hilaire** [comment]
Hello tosscaster,

We have not created the node `index.js` file yet, we will consider this issue in a further release.
For now, you can simply import the jmap client with `var jmap = require('./node_modules/jmap-client/dist/jmap-client.js');`.

Then you can start to play with the lib using ES6 like :

```
new jmap.Client(new jmap.RequestTransport(new jmap.QPromiseProvider()))
  .withAPIUrl('http://my-jmap-server/api')
  .getMailboxes().then(function(mailboxes) {
    console.log(mailboxes);
  });
```

And you can for example run it using the node-babel tool:

```
npm install --save-dev babel-cli
babel-node index.js
```

Cheers :)
